In [1]:
# Importamos las librerías necesarias

import pandas as pd
import numpy as numpy

pd.set_option("display.max_columns", None)

import seaborn as sns
import matplotlib.pyplot as plt

Fase 1: Exploración y Limpieza
1. Exploración Inicial

In [3]:
df_clientes_vuelos = pd.read_csv("data/Customer_Flight_Activity.csv")

display(df_clientes_vuelos.head(2))

print("=" * 100)

display(df_clientes_vuelos.tail(2))

print("=" * 100)

display(df_clientes_vuelos.sample(2))

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,100018,2017,1,3,0,3,1521,152.0,0,0
1,100102,2017,1,10,4,14,2030,203.0,0,0

====================================================================================================

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
405622,999982,2018,12,0,0,0,0,0.0,0,0
405623,999986,2018,12,0,0,0,0,0.0,0,0

====================================================================================================

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
219119,968034,2018,1,1,0,1,1599,159.0,0,0
148172,857629,2017,7,17,4,21,5292,529.0,844,68

In [4]:
print(f"El dataframe clientes tiene {df_clientes_vuelos.shape[0]} filas y {df_clientes_vuelos.shape[1]} columnas")

El dataframe clientes tiene 405624 filas y 10 columnas

In [5]:
df_clientes_perfil = pd.read_csv("data/Customer_Loyalty_History.csv")

display(df_clientes_perfil.head(2))

print("=" * 100)

display(df_clientes_perfil.tail(2))

print("=" * 100)

display(df_clientes_perfil.sample(2))

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN

====================================================================================================

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
16735,906428,Canada,Yukon,Whitehorse,Y2K 6R0,Male,Bachelor,-57297.0,Married,Star,10018.66,2018 Promotion,2018,4,NaN,NaN
16736,652627,Canada,Manitoba,Winnipeg,R2C 0M5,Female,Bachelor,75049.0,Married,Star,83325.38,Standard,2015,12,2016.0,8.0

====================================================================================================

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
1276,103352,Canada,Quebec,Montreal,H2T 9K8,Male,Bachelor,69742.0,Married,Aurora,5555.49,Standard,2014,11,2015.0,9.0
2001,588943,Canada,Ontario,Toronto,M2M 7K8,Male,College,NaN,Married,Aurora,7281.44,Standard,2018,1,2018.0,9.0

In [6]:
print(f"El dataframe clientes tiene {df_clientes_perfil.shape[0]} filas y {df_clientes_perfil.shape[1]} columnas")

El dataframe clientes tiene 16737 filas y 16 columnas

In [7]:
df_clientes_vuelos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405624 entries, 0 to 405623
Data columns (total 10 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Loyalty Number               405624 non-null  int64
 1   Year                         405624 non-null  int64
 2   Month                        405624 non-null  int64
 3   Flights Booked               405624 non-null  int64
 4   Flights with Companions      405624 non-null  int64
 5   Total Flights                405624 non-null  int64
 6   Distance                     405624 non-null  int64
 7   Points Accumulated           405624 non-null  float64
 8   Points Redeemed              405624 non-null  int64
 9   Dollar Cost Points Redeemed  405624 non-null  int64
dtypes: float64(1), int64(9)
memory usage: 30.9 MB

In [9]:
df_clientes_perfil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16737 entries, 0 to 16736
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loyalty Number      16737 non-null  int64
 1   Country             16737 non-null  object
 2   Province            16737 non-null  object
 3   City                16737 non-null  object
 4   Postal Code         16737 non-null  object
 5   Gender              16737 non-null  object
 6   Education           16737 non-null  object
 7   Salary              12499 non-null  float64
 8   Marital Status      16737 non-null  object
 9   Loyalty Card        16737 non-null  object
 10  CLV                 16737 non-null  float64
 11  Enrollment Type     16737 non-null  object
 12  Enrollment Year     16737 non-null  int64
 13  Enrollment Month    16737 non-null  int64
 14  Cancellation Year   2067 non-null   float64
 15  Cancellation Month  2067 non-null   float64
dtypes: float64(4), int64(3), object(9)
memory usage: 2.0+ MB