In [302]:
# Importamos las librerías necesarias

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

import seaborn as sns
import matplotlib.pyplot as plt

Fase 1: Exploración y Limpieza
1. Exploración Inicial

In [303]:
df_clientes_vuelos = pd.read_csv("data/Customer_Flight_Activity.csv")
df_clientes_perfil = pd.read_csv("data/Customer_Loyalty_History.csv")

In [304]:
# Funcion para exploración básica

def exploracion_basica(df, nombre="Dataframe"):
    print(f"\n Exploración de: {nombre}")
    print("\n .head, datos primeros")
    display(df.head(2))
    print("=" * 100)
    print("\n .tail, datos finales")
    display(df.tail(2))
    print("=" * 100)
    print("\n .sample,datos aleatorios")
    display(df.sample(2))
    print("=" * 100)
    print("\n Información:")
    print(df.info())
    print("=" * 100)
    print(f"El dataframe tiene {df.shape[0]} filas y {df.shape[1]} columnas")

In [305]:
exploracion_basica(df_clientes_vuelos, "Clientes Vuelos")
exploracion_basica(df_clientes_perfil, "Clientes Perfil")

 Exploración de: Clientes Vuelos

 .head, datos primeros

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,100018,2017,1,3,0,3,1521,152.0,0,0
1,100102,2017,1,10,4,14,2030,203.0,0,0

====================================================================================================

 .tail, datos finales

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
405622,999982,2018,12,0,0,0,0,0.0,0,0
405623,999986,2018,12,0,0,0,0,0.0,0,0

====================================================================================================

 .sample,datos aleatorios

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
149538,860809,2017,9,5,0,5,395,39.0,0,0
2789,108346,2017,1,0,0,0,0,0.0,0,0

====================================================================================================

 Información:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405624 entries, 0 to 405623
Data columns (total 10 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Loyalty Number               405624 non-null  int64
 1   Year                         405624 non-null  int64
 2   Month                        405624 non-null  int64
 3   Flights Booked               405624 non-null  int64
 4   Flights with Companions      405624 non-null  int64
 5   Total Flights                405624 non-null  int64
 6   Distance                     405624 non-null  int64
 7   Points Accumulated           405624 non-null  float64
 8   Points Redeemed              405624 non-null  int64
 9   Dollar Cost Points Redeemed  405624 non-null  int64
dtypes: float64(1), int64(9)
memory usage: 30.9 MB
None
====================================================================================================
El dataframe tiene 405624 filas y 10 columnas

 Exploración de: Clientes Perfil

 .head, datos primeros

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN

====================================================================================================

 .tail, datos finales

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
16735,906428,Canada,Yukon,Whitehorse,Y2K 6R0,Male,Bachelor,-57297.0,Married,Star,10018.66,2018 Promotion,2018,4,NaN,NaN
16736,652627,Canada,Manitoba,Winnipeg,R2C 0M5,Female,Bachelor,75049.0,Married,Star,83325.38,Standard,2015,12,2016.0,8.0

====================================================================================================

 .sample,datos aleatorios

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
1780,802196,Canada,Quebec,Quebec City,G1B 3L5,Male,Bachelor,73602.0,Married,Aurora,6689.02,Standard,2015,9,NaN,NaN
15041,865803,Canada,Ontario,Sudbury,M5V 1G5,Male,Bachelor,73671.0,Married,Star,8355.64,Standard,2016,11,NaN,NaN

====================================================================================================

 Información:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16737 entries, 0 to 16736
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loyalty Number      16737 non-null  int64
 1   Country             16737 non-null  object
 2   Province            16737 non-null  object
 3   City                16737 non-null  object
 4   Postal Code         16737 non-null  object
 5   Gender              16737 non-null  object
 6   Education           16737 non-null  object
 7   Salary              12499 non-null  float64
 8   Marital Status      16737 non-null  object
 9   Loyalty Card        16737 non-null  object
 10  CLV                 16737 non-null  float64
 11  Enrollment Type     16737 non-null  object
 12  Enrollment Year     16737 non-null  int64
 13  Enrollment Month    16737 non-null  int64
 14  Cancellation Year   2067 non-null   float64
 15  Cancellation Month  2067 non-null   float64
dtypes: float64(4), int64(3), object(9)
memory usage: 2.0+ MB
None
====================================================================================================
El dataframe tiene 16737 filas y 16 columnas

##  Conclusiones del análisis de datos

Según los datos obtenidos, podemos extraer las siguientes conclusiones:

- Las columnas de ambos archivos presentan una estructura homogénea en cuanto a nomenclatura, siguiendo el formato de primera letra en mayúscula y el resto en minúsculas.
- Pero vamos a unir las nombres que estan separados por un espacio y unirlos por un guion bajo. ✅

- Se ha detectado que en la columna **Enrollment Type** existen valores que combinan el año y la categoría de forma repetida, por lo que sería necesario realizar una limpieza o transformación de estos datos en el DataFrame de **df_clientes_perfil**. ✅

- El DataFrame **df_clientes_vuelos** contiene un mayor número de filas que **df_clientes_perfil**, lo cual es coherente, ya que un mismo cliente puede realizar múltiples vuelos.
La Relación entre tablas es 1:N y se conectan por Loyalty Number.

###  df_clientes_vuelos

- No se han identificado valores nulos.

###  df_clientes_perfil

- Se han identificado valores nulos en:
  - **Salary**: 4.238 nulos  
  - **Cancellation Year**: 14.670 nulos  
  - **Cancellation Month**: 14.670 nulos
  - En Cancellation Year y Month hay muchos nulos, muchos clientes que no han cancelado.

- Sería recomendable cambiar el tipo de dato de las columnas:
  - **Cancellation Year** → entero  
  - **Cancellation Month** → entero 
  - Ya que no tiene sentido tenerlos como float siendo enteros el año y mes. Tener en cuenta que tiene nulos a la hora de pasarlo a entero, ya que panda los convierte a float.
  - Los valores nulos en Cancellation Year y Cancellation Month probablemente indican que el cliente no ha cancelado. Podemos dejarlos en nulo y con la función Int64 pasar el tipo de dato a entero y añadir una columna de Cancelled que nos indique si ha cancelado o no con algun valor ejemplo 0/1 o si/no.
  - Pero tambien tenemos que fijarnos en que los dos valores de las columnas de year y month esten completas para que nos identifique si hay algun error en esos datos y se cumpla la condición. ✅

- Me he dado cuenta que en Salary tambien aparece datos en negativo. Un salario no puede ser negativo, por lo cual es un dato erroneo. No sabemos el valor real, al igual que los nulos.
Vamos a converir estos datos en negativo a nulos y luego vemos que hacemos con ellos.✅

2. Limpieza de Datos

In [306]:
df_clientes_vuelos.columns

Index(['Loyalty Number', 'Year', 'Month', 'Flights Booked',
       'Flights with Companions', 'Total Flights', 'Distance',
       'Points Accumulated', 'Points Redeemed', 'Dollar Cost Points Redeemed'],
      dtype='object')

In [307]:
def limpiar_columnas(df):
    nuevas_cols = {
        col: col.strip().lower().replace(" ", "_")
        for col in df.columns
    }
    df.rename(columns=nuevas_cols, inplace=True)
    return df

In [308]:
df_clientes_vuelos = limpiar_columnas(df_clientes_vuelos)

df_clientes_vuelos

,loyalty_number,year,month,flights_booked,flights_with_companions,total_flights,distance,points_accumulated,points_redeemed,dollar_cost_points_redeemed
0,100018,2017,1,3,0,3,1521,152.0,0,0
1,100102,2017,1,10,4,14,2030,203.0,0,0
2,100140,2017,1,6,0,6,1200,120.0,0,0
3,100214,2017,1,0,0,0,0,0.0,0,0
4,100272,2017,1,0,0,0,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...
405619,999902,2018,12,0,0,0,0,0.0,0,0
405620,999911,2018,12,0,0,0,0,0.0,0,0
405621,999940,2018,12,3,0,3,1233,123.0,0,0
405622,999982,2018,12,0,0,0,0,0.0,0,0
405623,999986,2018,12,0,0,0,0,0.0,0,0

In [309]:
df_clientes_perfil = limpiar_columnas(df_clientes_perfil)

df_clientes_perfil

,loyalty_number,country,province,city,postal_code,gender,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013,2,NaN,NaN
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,10,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16732,823768,Canada,British Columbia,Vancouver,V6E 3Z3,Female,College,NaN,Married,Star,61850.19,Standard,2012,12,NaN,NaN
16733,680886,Canada,Saskatchewan,Regina,S1J 3C5,Female,Bachelor,89210.0,Married,Star,67907.27,Standard,2014,9,NaN,NaN
16734,776187,Canada,British Columbia,Vancouver,V5R 1W3,Male,College,NaN,Single,Star,74228.52,Standard,2014,3,NaN,NaN
16735,906428,Canada,Yukon,Whitehorse,Y2K 6R0,Male,Bachelor,-57297.0,Married,Star,10018.66,2018 Promotion,2018,4,NaN,NaN
16736,652627,Canada,Manitoba,Winnipeg,R2C 0M5,Female,Bachelor,75049.0,Married,Star,83325.38,Standard,2015,12,2016.0,8.0

In [310]:
# Ver valores antes de limpiar
df_clientes_perfil["enrollment_type"].value_counts()

enrollment_type
Standard          15766
2018 Promotion      971
Name: count, dtype: int64

In [311]:
# Limpiar enrollment_type dejando solo la categoría
df_clientes_perfil["enrollment_type"] = df_clientes_perfil["enrollment_type"].str.replace(r"^\d{4}\s*", "", regex=True).str.strip()

In [312]:
# Ver valores despues de limpiar
df_clientes_perfil["enrollment_type"].value_counts()

enrollment_type
Standard     15766
Promotion      971
Name: count, dtype: int64

In [313]:
df_clientes_perfil[
    df_clientes_perfil["cancellation_year"].notnull() &
    df_clientes_perfil["cancellation_month"].isnull()
]

Empty DataFrame
Columns: [loyalty_number, country, province, city, postal_code, gender, education, salary, marital_status, loyalty_card, clv, enrollment_type, enrollment_year, enrollment_month, cancellation_year, cancellation_month]
Index: []

In [314]:
df_clientes_perfil[
    df_clientes_perfil["cancellation_year"].isnull() &
    df_clientes_perfil["cancellation_month"].notnull()
]

Empty DataFrame
Columns: [loyalty_number, country, province, city, postal_code, gender, education, salary, marital_status, loyalty_card, clv, enrollment_type, enrollment_year, enrollment_month, cancellation_year, cancellation_month]
Index: []

In [315]:
df_clientes_perfil["cancelled"] = (
    df_clientes_perfil["cancellation_year"].notnull() |
    df_clientes_perfil["cancellation_month"].notnull()
).astype(int)

In [316]:
df_clientes_perfil.head(5)

,loyalty_number,country,province,city,postal_code,gender,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month,cancelled
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN,0
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN,0
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0,1
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013,2,NaN,NaN,0
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,10,NaN,NaN,0

In [317]:
def convertir_Int64(df, columnas):
    for col in columnas:
        df[col] = df[col].astype("Int64")
    return df

In [318]:
df_clientes_perfil = convertir_Int64(df_clientes_perfil, ["cancellation_year", "cancellation_month"])

In [319]:
df_clientes_perfil.dtypes

loyalty_number          int64
country                object
province               object
city                   object
postal_code            object
gender                 object
education              object
salary                float64
marital_status         object
loyalty_card           object
clv                   float64
enrollment_type        object
enrollment_year         int64
enrollment_month        int64
cancellation_year       Int64
cancellation_month      Int64
cancelled               int64
dtype: object

In [320]:
df_clientes_perfil.loc[df_clientes_perfil["salary"] < 0, "salary"] = np.nan

In [321]:
df_clientes_perfil.tail(2)

,loyalty_number,country,province,city,postal_code,gender,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month,cancelled
16735,906428,Canada,Yukon,Whitehorse,Y2K 6R0,Male,Bachelor,NaN,Married,Star,10018.66,Promotion,2018,4,<NA>,<NA>,0
16736,652627,Canada,Manitoba,Winnipeg,R2C 0M5,Female,Bachelor,75049.0,Married,Star,83325.38,Standard,2015,12,2016,8,1

Fase 2 : Análisis Estadistico

1. Análisis de variables numéricas:
    1. Estadísticas descriptivas (media, mediana, moda, desviación estándar, etc.) de las variables
    numéricas relevantes.
    2. Identificación de valores atípicos en las variables numéricas.
    3. Análisis de correlación entre variables numéricas.

2. Análisis de variables categóricas:
    1. Distribución de frecuencias de las variables categóricas relevantes.

In [322]:
def analisis_estadistico(df):
    print("🔹 NUMÉRICAS")
    display(df.describe(include = "number").T)
    
    print("\n🔹 CATEGÓRICAS")
    display(df.describe(include="object").T)

In [323]:
df_clientes_vuelos = analisis_estadistico(df_clientes_vuelos)

🔹 NUMÉRICAS

,count,mean,std,min,25%,50%,75%,max
loyalty_number,405624.0,550037.873084,258935.286969,100018.0,326961.00,550834.0,772194.00,999986.0
year,405624.0,2017.500000,0.500001,2017.0,2017.00,2017.5,2018.00,2018.0
month,405624.0,6.500000,3.452057,1.0,3.75,6.5,9.25,12.0
flights_booked,405624.0,4.115052,5.225518,0.0,0.00,1.0,8.00,21.0
flights_with_companions,405624.0,1.031805,2.076869,0.0,0.00,0.0,1.00,11.0
total_flights,405624.0,5.146858,6.521227,0.0,0.00,1.0,10.00,32.0
distance,405624.0,1208.880059,1433.155320,0.0,0.00,488.0,2336.00,6293.0
points_accumulated,405624.0,123.692721,146.599831,0.0,0.00,50.0,239.00,676.5
points_redeemed,405624.0,30.696872,125.486049,0.0,0.00,0.0,0.00,876.0
dollar_cost_points_redeemed,405624.0,2.484503,10.150038,0.0,0.00,0.0,0.00,71.0

🔹 CATEGÓRICAS

ValueError: No objects to concatenate

## Análisis de variables numéricas (df_clientes_vuelos)

- Observamos que tenemos 405.624 registros en total.

- Como ya sabiamos no aparecen nulos.

- Variables como **flights_booked**, **points_redeemed** y **dollar_cost_points_redeemed** presentan una alta concentración de valores 0, lo que sugiere que una gran parte de los clientes tiene baja o nula actividad.

- La variable **points_accumulated** tiene valores decimales, tendremos que revisar el tipo de dato.

- Las variables **loyarty_number**, **year**, **month**, son variables que no nos dicen nada, identificadores numericos.

- En general, se identifica una distribución sesgada en varias variables, con presencia de valores extremos que pueden influir en la media.

## Análisis de variables categoricas

- Nos da error en el DataFrame de pd_clientes_vuelos, porque el tipo de dato es numérico y no tiene ningun dato categórico.
En este DataFrame no se podria analizar.

## Análisis de variables numéricas (df_clientes_vuelos)

- Observamos que tenemos 405.624 registros en total.

- No se han detectado valores nulos en este DataFrame.

- Variables como **flights_booked**, **points_redeemed** y **dollar_cost_points_redeemed** tienen muchos valores 0, lo que indica que muchos clientes tienen poca o ninguna actividad.

- La variable **points_accumulated** tiene valores decimales, por lo que sería conveniente revisar si debería ser un número entero.

- Las variables **loyalty_number**, **year** y **month** no aportan información relevante para el análisis.

- En general, los datos presentan bastante diferencia entre unos clientes y otros, con algunos valores muy altos que pueden afectar a la media.

## Análisis de variables categóricas

- No se han podido analizar variables categóricas en este DataFrame, ya que todas las columnas son numéricas y no hay variables de tipo texto.

In [ ]:
df_clientes_perfil = analisis_estadistico(df_clientes_perfil)

🔹 NUMÉRICAS

,count,mean,std,min,25%,50%,75%,max
loyalty_number,16737.0,549735.880445,258912.132453,100018.0,326603.0,550434.0,772019.0,999986.0
salary,12479.0,79429.572642,34727.560404,15609.0,59265.0,73510.0,88600.5,407228.0
clv,16737.0,7988.896536,6860.98228,1898.01,3980.84,5780.18,8940.58,83325.38
enrollment_year,16737.0,2015.253211,1.979111,2012.0,2014.0,2015.0,2017.0,2018.0
enrollment_month,16737.0,6.669116,3.398958,1.0,4.0,7.0,10.0,12.0
cancellation_year,2067.0,2016.503145,1.380743,2013.0,2016.0,2017.0,2018.0,2018.0
cancellation_month,2067.0,6.962748,3.455297,1.0,4.0,7.0,10.0,12.0
cancelled,16737.0,0.123499,0.329019,0.0,0.0,0.0,0.0,1.0

🔹 CATEGÓRICAS

                 count unique       top   freq
country          16737      1    Canada  16737
province         16737     11   Ontario   5404
city             16737     29   Toronto   3351
postal_code      16737     55   V6E 3D9    911
gender           16737      2    Female   8410
education        16737      5  Bachelor  10475
marital_status   16737      3   Married   9735
loyalty_card     16737      3      Star   7637
enrollment_type  16737      2  Standard  15766

## Análisis de variables numéricas (df_clientes_perfil)

- Observamos que tenemos 405.624 registros en total.

- La variable **salary** tiene valores nulos y bastante diferencia entre unos clientes y otros. Además, hay algunos salarios muy altos que pueden ser valores atípicos.

- La variable **clv (customer_lifetime_value)** también varía mucho, lo que indica que hay clientes que generan mucho más valor que otros.

- Las columnas **cancellation_year** y **cancellation_month** solo tienen datos en los clientes que han cancelado. Cuando están vacías (NaN), significa que el cliente sigue activo.

- La variable **cancelled** muestra que aproximadamente el **12,3% de los clientes ha cancelado**, mientras que el **87,7% sigue activo**.

- Las variables **enrollment_year** y **enrollment_month** indican que la mayoría de los clientes se registraron en los últimos años.

## Análisis de variables categóricas (df_clientes_perfil)

- La variable **country** solo tiene un valor (Canada), por lo que no aporta información útil.

- La variable **province** tiene 11 valores distintos, siendo **Ontario** la más común.

- La variable **city** incluye 29 ciudades diferentes, destacando **Toronto** como la más frecuente.

- La variable **postal_code** tiene muchos valores distintos, lo que indica variedad en la ubicación de los clientes.

- La variable **gender** tiene dos categorías, con una mayoría de mujeres.

- La variable **education** tiene 5 niveles, siendo **Bachelor** el más habitual.

- La variable **marital_status** tiene 3 categorías, predominando los clientes casados.

- La variable **loyalty_card** tiene 3 tipos, siendo **Star** el más común.

- La variable **enrollment_type** tiene 2 categorías, donde **Standard** es la más frecuente.

In [ ]:
print(df_clientes_vuelos.duplicated().sum())
print(df_clientes_perfil.duplicated().sum())

0
0

- Miramos si los DataFrame tienen duplicados, en este caso no tiene.

In [324]:
df_clientes_perfil["salary"] = df_clientes_perfil.groupby("education")["salary"].transform(
    lambda x: x.fillna(x.mean())
)

- Los valores nulos de salary se han rellenado utilizando la media dentro de cada nivel educativo.

In [325]:
df_clientes_perfil.head(5)

,loyalty_number,country,province,city,postal_code,gender,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month,cancelled
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,<NA>,<NA>,0
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,<NA>,<NA>,0
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018,1,1
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013,2,<NA>,<NA>,0
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,10,<NA>,<NA>,0

In [ ]:
df_clientes_perfil["salary"] = df_clientes_perfil["salary"].fillna(df_clientes_perfil["salary"].mean()
)

- En los casos donde no había datos suficientes para calcular esa media, se ha utilizado la media general de todos los clientes.

In [335]:
df_clientes_perfil["salary"] = df_clientes_perfil["salary"].round(2)

- Se ha redondeado la variable salary a dos decimales para mejorar la legibilidad de los datos.

In [336]:
df_clientes_perfil.head(5)

,loyalty_number,country,province,city,postal_code,gender,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month,cancelled
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,<NA>,<NA>,0
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,79417.8,Divorced,Star,3839.61,Standard,2016,3,<NA>,<NA>,0
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,79417.8,Single,Star,3839.75,Standard,2014,7,2018,1,1
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,79417.8,Single,Star,3839.75,Standard,2013,2,<NA>,<NA>,0
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,10,<NA>,<NA>,0

In [329]:
df_clientes_vuelos["points_accumulated"] = (df_clientes_vuelos["points_accumulated"].round().astype(int))

- Pasamos el dato de float a entero, más, real como puntos.

In [330]:
df_clientes_vuelos.head(5)

,loyalty_number,year,month,flights_booked,flights_with_companions,total_flights,distance,points_accumulated,points_redeemed,dollar_cost_points_redeemed
0,100018,2017,1,3,0,3,1521,152,0,0
1,100102,2017,1,10,4,14,2030,203,0,0
2,100140,2017,1,6,0,6,1200,120,0,0
3,100214,2017,1,0,0,0,0,0,0,0
4,100272,2017,1,0,0,0,0,0,0,0